worker_processes 1;

events {
    worker_connections 1024;
}

http {

    include mime.types;
    default_type application/octet-stream;
    sendfile on;

    log_format main '$remote_addr - $remote_user upstream: $upstream_addr';

    access_log logs/access.log main;
    error_log logs/error.log;

    upstream backend {
        ip_hash;
        server localhost:5001 max_fails=3 fail_timeout=30s;
        server localhost:5002 max_fails=3 fail_timeout=30s;
    }
    
    server {
        listen 8080;
        server_name localhost;

        location /rankHub {
            proxy_pass http://backend/rankHub;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
